# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- bash: export PRODUCTS_VERSION=$(jq -r ".version" < products-service/package.json)
- task: Docker@1
  displayName: 'Build products-service'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: bricerisingslalom
    arguments: '-t docker.io/bricerisingslalom/products-service:latest'
- task: Docker@1
  displayName: 'Push products-service'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: bricerisingslalom
    command: 'Push an image'
    arguments: 'docker.io/bricerisingslalom/products-service:latest'
