# Language setting http://docs.shippable.com/ci/languages/node/
language: node_js

# use this to control what branches get built.
# http://docs.shippable.com/ci/advancedOptions/branches/
branches:
  only:
    - master

build:
  ci:
    - catalog-service/cicd-scripts/build.sh
    - products-service/cicd-scripts/build.sh
  post_ci:
    - shipctl post_resource_state catalog-service-image versionName $BRANCH.$BUILD_NUMBER
    - shipctl post_resource_state products-service-image versionName $BRANCH.$BUILD_NUMBER

resources:
  - name: catalog-service-image
    type: image
    pointer:
      sourceName: "docker.io/bricerisingslalom/catalog-service"
    seed:
      versionName: "latest"
  - name: products-service-image
    type: image
    pointer:
      sourceName: "docker.io/bricerisingslalom/products-service"
    seed:
      versionName: "latest"

jobs:
  - name: catalog-application_runCI
    type: runCI
    integration: docker hub - bricerisingslalom
    steps:
      - OUT: catalog-service-image
      - OUT: products-service-image
  - name: catalog-application_deploy
    type: runSh
    triggerMode: serial
    dependencyMode: immediate
    integrations:
      - integrationName: eks-cluster
        type: kubernetes
    steps:
      - IN: catalog-service-image
        versionName: latest
      - IN: products-service-image
        versionName: latest
      - TASK:
          name: deploy-to-eks
          script:
            - products-service/scripts/deploy.sh
            - catalog-service/scripts/deploy.sh

integrations:

  # http://docs.shippable.com/ci/shippableyml/#notifications
  notifications:
  # turning of email for PR builds, get notified only on failure and change in status
  # http://docs.shippable.com/integrations/notifications/email/
    - integrationName: email
      type: email
      on_success: change
      on_failure: always
      on_pull_request: never

  hub:
    - integrationName: docker hub - bricerisingslalom
      type: dockerRegistryLogin
  
  eks:
    - integrationName: eks-cluster
      type: kubernetes
