apiVersion: v1
kind: Service
metadata:
  name: products-service
  annotations:
spec:
  type: LoadBalancer
  selector:
    app: products-service
  ports:
    - name: products-service-port
      protocol: TCP
      port: 3000
      targetPort: 3000
